spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
